# Generated by Django 5.0.7 on 2024-07-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='room_number',
        ),
    ]
