# Generated by Django 5.0.7 on 2024-07-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_hotel_address_hotel_created_at_hotel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
